// <auto-generated />
namespace DailyStatement.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddInversePropertyForProjectv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInversePropertyForProjectv2));
        
        string IMigrationMetadata.Id
        {
            get { return "201305200604258_Add-InversePropertyForProjectv2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
