// <auto-generated />
namespace DailyStatement.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddMetaData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMetaData));
        
        string IMigrationMetadata.Id
        {
            get { return "201302220730417_AddMetaData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
